version: '3.9'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=microbot
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=microbot
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U microbot"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: microbot-app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://microbot:securepassword@db:5432/microbot
    volumes:
      - ./sessions:/microbot/sessions
      - ./logs:/microbot/logs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: 