version: '3.9'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=microbot
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=microbot_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U microbot"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: microbot-app-dev
    env_file:
      - .env.dev
    environment:
      - DATABASE_URL=postgresql://microbot:devpassword@db:5432/microbot_dev
      - DEBUG=True
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/microbot  # Tüm kodları container içine bağla
      - ./sessions:/microbot/sessions
      - ./logs:/microbot/logs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Geliştirme için yararlı extra servisler
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db

volumes:
  postgres_data_dev: 